config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations]
  get "up" => "rails/health#show", as: :rails_health_check

  root 'pages#home'

  resources :positions, only: [:create] do
    resources :position_criteriums, only: [:new, :create, :destroy]
  end

  resources :job_applications, only: [:new, :create, :show, :update]

  patch '/job_applications/:id/validate_cv', to: 'job_applications#validate_cv', as: :validate_cv
  get '/job_applications/:id/view_cv', to: 'job_applications#view_cv', as: :view_cv
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :user
  belongs_to :position

  has_many :job_application_requirements, dependent: :destroy
  has_many :position_criteriums, through: :job_application_requirements

  validates :cv_text, presence: true
  validates :applicant_full_name, presence: true

  enum status: { in_process: 0, rejected: 1, accepted: 2, on_hold: 3 }

  def all_required_criteriums_satisfied?
    job_application_requirements.each do |req|
      next unless req.position_criterium.required

      return false unless req.satisfied
    end

    true
  end

  def all_bonus_criteriums_satisfied?
    job_application_requirements.each do |req|
      next if req.position_criterium.required

      return false unless req.satisfied
    end

    true
  end
end

app/models/job_application_requirement.rb
class JobApplicationRequirement < ApplicationRecord
  belongs_to :job_application
  belongs_to :position_criterium

  def satisfy!
    self.satisfied = true
    self.save!
  end
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :user

  has_many :position_criteriums, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/position_criterium.rb
class PositionCriterium < ApplicationRecord
  belongs_to :position
  has_many :job_application_requirements

  validates :criteria_value, presence: true

  scope :required, -> { where(required: true) }
  scope :not_required, -> { where(required: false) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  def new
    @job_application = JobApplication.new
  end

  def create
    @job_application = JobApplication.new(job_application_params)
    @job_application.user = current_user

    if @job_application.valid? && @job_application.save
      @job_application.position.position_criteriums.each do |crit|
        @job_application.job_application_requirements.create(position_criterium: crit)
      end

      redirect_to job_application_path(@job_application)
    else
      redirect_to root_path, alert: 'Dogodila se greška. Pokušajte ponovno.'
    end
  end

  def show
    @job_application = JobApplication.find(params[:id])
  end

  def validate_cv
    @job_application = JobApplication.find(params[:id])

    CvValidator.new(@job_application).validate

    redirect_to job_application_path(@job_application)
  end

  def view_cv
    @job_application = JobApplication.find(params[:id])
  end

  def update
    @job_application = JobApplication.find(params[:id])

    if @job_application.update(update_params)
      redirect_to job_application_path(@job_application)
    else
      redirect_to job_application_path(@job_application), alert: "Dogodila se greška. Pokušajte ponovno."
    end
  end

  private

  def job_application_params
    params.require(:job_application).permit(
      :applicant_full_name,
      :applicant_phone_number,
      :applicant_oib,
      :applicant_address,
      :cv_text,
      :position_id
    )
  end

  def update_params
    params.permit(:status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
end

app/controllers/position_criteriums_controller.rb
class PositionCriteriumsController < ApplicationController
  def new
    @position = Position.find(params[:position_id])
  end

  def create
    @position = Position.find(params[:position_id])
    @position_criterium = @position.position_criteriums.new(criterium_params)

    if @position_criterium.valid? && @position_criterium.save
      redirect_to new_position_position_criterium_path(@position)
    else
      redirect_to new_position_position_criterium_path(@position), alert: 'Nešto je pošlo po krivu. Probajte ponovno.'
    end
  end

  def destroy
    @position = Position.find(params[:position_id])
    @position_criterium = @position.position_criteriums.find(params[:id])

    if @position_criterium.destroy
      redirect_to new_position_position_criterium_path(@position)
    else
      redirect_to new_position_position_criterium_path(@position), alert: 'Nešto je pošlo po krivu. Probajte ponovno.'
    end
  end

  private

  def criterium_params
    params.permit(:criteria_value, :required)
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  def create
    position = Position.new(position_params)
    position.user = current_user

    if position.valid? && position.save
      redirect_to root_path
    else
      redirect_to root_path, alert: 'Nešto je pošlo po krivu. Pokušajte ponovno.'
    end
  end

  private

  def position_params
    params.require(:position).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/status_helper.rb
module StatusHelper
  def status_name(status)
    case status
    when 'in_process'
      'U toku'
    when 'rejected'
      'Odbijena'
    when 'accepted'
      'Prihvaćena'
    when 'on_hold'
      'Na čekanju'
    end
  end

  def status_color(status)
    case status
    when 'in_process'
      'yellow'
    when 'rejected'
      'red'
    when 'accepted'
      'green'
    when 'on_hold'
      'orange'
    end
  end
end

app/views/job_applications/new.html.erb
<%= render "layouts/navigation" %>

<div class="flex flex-col items-center">
  <div class="container p-10">
    <h1 class="text-2xl font-bold border-b-2 border-primary">Nova prijava</h1>

    <%= form_with model: @job_application, method: :post do |form| %>
      <div class="mt-4 ">
        <%= form.label :applicant_full_name, "Ime i prezime kandidata (obvezno)", class: "block mb-2 text-sm font-medium text-gray-900" %>
        <%= form.text_field :applicant_full_name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" %>
      </div>
      <div class="mt-4 ">
        <%= form.label :applicant_address, "Adresa kandidata", class: "block mb-2 text-sm font-medium text-gray-900" %>
        <%= form.text_field :applicant_address, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" %>
      </div>
      <div class="mt-4 ">
        <%= form.label :applicant_phone_number, "Broj mobitela kandidata", class: "block mb-2 text-sm font-medium text-gray-900" %>
        <%= form.text_field :applicant_phone_number, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" %>
      </div>
      <div class="mt-4 ">
        <%= form.label :applicant_oib, "OIB kandidata", class: "block mb-2 text-sm font-medium text-gray-900" %>
        <%= form.text_field :applicant_oib, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" %>
      </div>
      <div class="mt-4">
        <%= form.label :position_id, "Pozicija", class: "block mb-2 text-sm font-medium text-gray-900" %>
        <%= form.select :position_id, options_for_select(Position.all.map {|pos| [pos.name, pos.id]}), {}, { class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" } %>
      </div>
      <div class="mt-4">
        <%= form.label :cv_text, "CV", class: "block mb-2 text-sm font-medium text-gray-900" %>
        <%= form.text_area :cv_text, rows: 5, class: "block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-primary-500 focus:border-primary-500" %>
      </div>

      <button type="submit" class="mt-4 text-white bg-primary hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Spremi</button>
  <% end %>
  </div>
</div>

app/views/job_applications/show.html.erb
<%= render "layouts/navigation" %>

<div class="flex flex-col items-center">
  <div class="container p-10">
    <h1 class="text-2xl font-bold border-b-2 border-primary">Prijava: <%= @job_application.applicant_full_name %> - <%= @job_application.position.name %></h1>

    <div class="flex items-center gap-4 mt-4">
      <div class="flex items-center gap-2">
        <svg class="w-6 h-6 text-gray-800" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-width="2" d="M7 17v1a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-1a3 3 0 0 0-3-3h-4a3 3 0 0 0-3 3Zm8-9a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
        </svg>

        <p><%= @job_application.applicant_full_name %></p>
      </div>
      <div class="flex items-center gap-2">
        <svg class="w-6 h-6 text-gray-800" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 4h12M6 4v16M6 4H5m13 0v16m0-16h1m-1 16H6m12 0h1M6 20H5M9 7h1v1H9V7Zm5 0h1v1h-1V7Zm-5 4h1v1H9v-1Zm5 0h1v1h-1v-1Zm-3 4h2a1 1 0 0 1 1 1v4h-4v-4a1 1 0 0 1 1-1Z"/>
        </svg>
        <p><%= @job_application.applicant_address %></p>
      </div>
      <div class="flex items-center gap-2">
        <svg class="w-6 h-6 text-gray-800" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.427 14.768 17.2 13.542a1.733 1.733 0 0 0-2.45 0l-.613.613a1.732 1.732 0 0 1-2.45 0l-1.838-1.84a1.735 1.735 0 0 1 0-2.452l.612-.613a1.735 1.735 0 0 0 0-2.452L9.237 5.572a1.6 1.6 0 0 0-2.45 0c-3.223 3.2-1.702 6.896 1.519 10.117 3.22 3.221 6.914 4.745 10.12 1.535a1.601 1.601 0 0 0 0-2.456Z"/>
        </svg>

        <p><%= @job_application.applicant_phone_number %></p>
      </div>
      <div class="flex items-center gap-2">
        <svg class="w-6 h-6 text-gray-800" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 9h3m-3 3h3m-3 3h3m-6 1c-.306-.613-.933-1-1.618-1H7.618c-.685 0-1.312.387-1.618 1M4 5h16a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1Zm7 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0Z"/>
        </svg>

        <p><%= @job_application.applicant_oib %></p>
      </div>
      <%= link_to view_cv_path(@job_application), class: "flex items-center gap-2 text-blue-700" do %>
        <svg class="w-6 h-6 text-blue-800" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-width="2" d="M21 12c0 1.2-4.03 6-9 6s-9-4.8-9-6c0-1.2 4.03-6 9-6s9 4.8 9 6Z"/>
          <path stroke="currentColor" stroke-width="2" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
        </svg>

        Pogledaj CV
      <% end %>
    </div>

    <% if @job_application.cv_processed_at.blank? %>
      <div id="alert-additional-content-4" class="mt-6 p-4 mb-4 text-yellow-800 border border-yellow-300 rounded-lg bg-yellow-50" role="alert">
        <div class="flex items-center">
          <svg class="flex-shrink-0 w-4 h-4 me-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
          </svg>
          <span class="sr-only">Info</span>
          <h3 class="text-lg font-medium">CV nije obrađen.</h3>
        </div>
        <div class="mt-2 mb-4 text-sm">
          CV od ovog kandidata još uvijek nije obrađen te kriteriji nisu točno validirani.
        </div>
        <div class="flex">
          <%= link_to validate_cv_path(@job_application.id), class: "text-white bg-yellow-800 hover:bg-yellow-900 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-xs px-3 py-1.5 me-2 text-center inline-flex items-center", data: { turbo_method: :patch } do %>
            <svg class="w-3 h-3 mr-2 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 12H4m12 0-4 4m4-4-4-4m3-4h2a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3h-2"/>
            </svg>
            Validiraj CV
          <% end %>
        </div>
      </div>
    <% else %>
      <div id="alert-additional-content-3" class="mt-6 p-4 mb-4 text-green-800 border border-green-300 rounded-lg bg-green-50" role="alert">
        <div class="flex items-center">
          <svg class="flex-shrink-0 w-4 h-4 me-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
          </svg>
          <span class="sr-only">Info</span>
          <h3 class="text-lg font-medium">CV Validiran!</h3>
        </div>
        <div class="mt-2 mb-4 text-sm">
          CV od ove prijave je već validiran i dostupni su rezultati validacije.
        </div>
        <div class="flex">
          <p>Validiran prije <%= time_ago_in_words(@job_application.cv_processed_at) %></p>
        </div>
      </div>

      <div class="mt-2 border border-gray-100 rounded-md p-4">
        <p class="text-green-700 text-red-700 hidden"></p>
        <p class="font-medium">Zaključak:</p>
        <ul class="max-w-md space-y-1 list-disc list-inside">
          <li class="text-<%= @job_application.all_required_criteriums_satisfied? ? "green" : "red" %>-700">Svi obvezni uvjeti su zadovoljeni</li>
          <li class="text-<%= @job_application.all_bonus_criteriums_satisfied? ? "green" : "red" %>-700">Svi bonus uvjeti su zadovoljeni</li>
        </ul>

        <div class="flex items-center gap-2 mt-4">
          <% if @job_application.status.in? ["in_process", "on_hold"] %>
            <%= link_to job_application_path(@job_application, status: "accepted"), class: "px-3 py-2 text-sm font-medium text-center inline-flex items-center text-white bg-green-700 rounded-lg hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-blue-300", data: { turbo_method: :patch } do %>
              <svg class="w-6 h-6 text-white mr-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 11.917 9.724 16.5 19 7.5"/>
              </svg>

              Prihvati
            <% end %>
            <%= link_to  job_application_path(@job_application, status: "rejected"), class: "px-3 py-2 text-sm font-medium text-center inline-flex items-center text-white bg-red-700 rounded-lg hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-blue-300", data: { turbo_method: :patch } do %>
              <svg class="w-6 h-6 text-white mr-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18 17.94 6M18 18 6.06 6"/>
              </svg>

              Odbij
            <% end %>
          <% end %>
          <% if @job_application.status != "on_hold" %>
            <%= link_to  job_application_path(@job_application, status: "on_hold"), class: "px-3 py-2 text-sm font-medium text-center inline-flex items-center text-white bg-orange-700 rounded-lg hover:bg-orange-800 focus:ring-4 focus:outline-none focus:ring-blue-300", data: { turbo_method: :patch } do %>
              <svg class="w-6 h-6 text-white mr-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                <path fill-rule="evenodd" d="M8 5a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h1a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2H8Zm7 0a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h1a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-1Z" clip-rule="evenodd"/>
              </svg>

              Na čekanje
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="flex flex-col">
      <% @job_application.job_application_requirements.each do |req| %>
        <div class="border border-gray-100 p-4 rounded-md mt-2 flex items-center justify-between">
          <div class="flex items-center gap-2">
            <p class="max-w-[60rem] break-all"><%= req.position_criterium.criteria_value %></p>
            <% if req.position_criterium.required %>
              <span class="bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded">Obvezan kriterij</span>
            <% else %>
              <span class="bg-yellow-100 text-yellow-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded">Bonus kriterij</span>
            <% end %>
          </div>
          <div>
            <% if req.satisfied %>
              <span class="bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded">Zadovoljen</span>
            <% else %>
              <span class="bg-red-100 text-red-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded">Nije zadovoljen</span>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/job_applications/view_cv.html.erb
<%= render "layouts/navigation" %>

<div class="flex flex-col items-center">
  <div class="container p-10">
    <h1 class="text-2xl font-bold border-b-2 border-primary">CV za: <%= @job_application.applicant_full_name %> - <%= @job_application.position.name %></h1>

    <%= link_to job_application_path(@job_application), class: "flex items-center gap-2 text-blue-700 my-4" do %>
      <svg class="w-6 h-6 text-blue-800" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14M5 12l4-4m-4 4 4 4"/>
      </svg>

      Nazad
    <% end %>

    <h1 class="font-bold text-2xl mb-2">Jednostavan pregled</h1>
    <%= simple_format(@job_application.cv_text) %>

    <h1 class="font-bold text-2xl my-2">Markdown pregled</h1>
    <%= Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true).render(@job_application.cv_text).html_safe %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TcvValidator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<!--    <p class="notice"><%#= notice %></p>-->
<!--    <p class="alert"><%#= alert %></p>-->
    <%= yield %>
  </body>
</html>

app/views/position_criteriums/new.html.erb
<%= render "layouts/navigation" %>

<div class="flex flex-col items-center">
  <div class="container p-10">
    <h1 class="text-2xl font-bold">Upravljanje kriterjima za <span class="border-b-2 border-primary"><%= @position.name %></span></h1>

    <% if @position.position_criteriums.blank? %>
      <div id="alert-border-1" class="mt-4 flex items-center p-4 mb-4 text-blue-800 border-t-4 border-blue-300 bg-blue-50" role="alert">
        <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
        </svg>
        <div class="ms-3 text-sm font-medium">
          Ova pozicija nema niti jedan kriterij.
        </div>
      </div>
    <% end %>

    <%= form_with url: position_position_criteriums_path(@position), method: :post do |form| %>
      <div class="flex gap-2 items-center mt-6">
        <div>
          <%#= form.label :criterium_value, "Kriterij", class: "block mb-2 text-sm font-medium text-gray-900" %>
          <%= form.text_field :criteria_value, class: "min-w-[30rem] bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-3", placeholder: "Kriterij" %>
        </div>
        <div>
          <div class="flex items-center px-4 border border-gray-200 rounded">
            <%= form.check_box :required, checked: true, class: "w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2" %>
            <%= form.label :required, "Obavezan kriterij", class: "w-full py-3 ms-2 text-sm font-medium text-gray-900" %>
          </div>
        </div>
        <div>
          <button type="submit" class="text-white bg-primary hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-3 text-center">Dodaj kriterij</button>
        </div>
      </div>
    <% end %>

    <p class="text-gray-600 my-4">
      Ovi kriteriji će se koristiti kao ključne riječi prilikom obrade priloženih dokumenata kako bi se potvrdilo jesu li svi kriteriji
      zadovoljeni.
    </p>

    <div class="relative overflow-x-auto shadow-md sm:rounded-lg mt-6">
      <table class="w-full text-sm text-left rtl:text-right text-gray-500">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50">
          <tr>
            <th scope="col" class="px-6 py-3">
              Kriterij
            </th>
            <th scope="col" class="px-6 py-3">
              Obvezan
            </th>
            <th scope="col" class="px-6 py-3">
              <span class="sr-only">Edit</span>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @position.position_criteriums.each do |crit| %>
            <tr class="bg-white border-b">
              <th scope="row" class="px-6 max-w-2xl py-4 font-medium text-gray-900 max-w-[25rem] break-all">
                <%= crit.criteria_value %>
              </th>
              <td class="px-6 py-4">
                <% if crit.required %>
                  <span class="bg-green-100 text-green-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded">DA</span>
                <% else %>
                  <span class="bg-yellow-100 text-yellow-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded">NE</span>
                <% end %>
              </td>
              <td class="px-6 py-4 text-right">
                <%= link_to "Ukloni", position_position_criterium_path(@position, crit), class: "font-medium text-red-600 hover:underline", data: { turbo_method: :delete } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>